import "./globals.css";
import RecoilRootProvider from "../recoil/recoilRootProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
      <div id="portal"></div>
    </html>
  );
}
